sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

after_success:
  - mvn jacoco:report coveralls:report

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "QpfLZCmeTQoSgERhlNmhSNaZaXfzw+l49hUay34eE2Vs3UTKVITw1IIIt8VFkK6AZfC47Sn+kggt89ArSJ0G6ypQFptfubGic2S9OOrZMDwOvnovquXW46BpDkOAaMmIy9B5QN6wsAyg/qk0Wl6SR25eFNZo8poK/HtH6UHvQwIS4P8IdegKJ2mPEtGL17zk8FeSNTIKkPjvGYMZRKFJcHDSg4BnAf0tha/9aTgkkxcQs/vZYmueQkx6UE6jzilGowzNpV1CcvpgppHnmTx6deFzDW60thoyKv7OPcemn8LCsklPhldYj1wxu0wUeD/ItNNDKRZpCghIG86Cb1Yxg9lXaRWdFAwqlKG2oHAAdAMvWs4kbttTeo9F5kGyGGSWnINPAv1HWckRIWtIWKqE/oxMUPpNzVUWGb+ffmfyBxHLXzxU43c4UtjA7vReg2LE5HlMU2X4BKO/MBgjeX70MXXvYezZhr1wxZqUV4upQ89SbT7X5npYz6gmCWHVEoGJTprzvQylJyz5eC7Bu/7yCalpaj3WE7Utc32Sr1phLyAVlR4UQsdfoqx24C/3dlHEIav8ZkcujcjRM3hJZt72ZZscYL+pS0sJbC3Ld2Mz/eKQiFiJ/JJiQpgNKBnclwxrEH3wqwDDlxmRVQIL8fL2oo5O+R4HKcpI2oFUB7xGpIY="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "qIiiZ1I0cwDIub7xGcaGsbmbymn6sDHxkSIsZNwArmkZmKdN51+jDCv3iTBSnJitKScXcQvGisZKORuWUjEakIyidYlxBZnpKv9FGxMpPHbLkpVXE2QKwq1JpXw8HbUgD4MHxzHm4ODgLhLqim/pImOxZCcnri7BldbuD6YZLp5GaQtu25g4Vt38Bfb9sCUTdOpzhpGwzVMCGZ0pBIM0UgrsuyO9rW71jJ9fqRZ5ksP53lP0asDgmJIUIvR96O072d7Wq3r+rsuqVqqFwzHPaPEupFtLDs3gEBBpqu+iVOpKTPfTNFBUKibhZesouZ522NWkvnbqR+Jm8g8ScbAmtId/iCt7pTGJG9n18OTMXSfG7GU4bMLK+3OtQ609ORv5whyEyzv9oV/0wujgoAJARSoHoTwStqZq0m10FYF56ccU/Z+llGlvLHoeNpCcQsciYMOC+1OhMRLontp7+Qvt1n/C+rFbTlwUnGMkyLeIYwdCOgU3ZROJ3CJAl+L8MJbWPTGQCBBkN/cDEE2ff6wgthrsF4UZf2kP+okGe6nXUn4rsmzWz4CINf00/SLvtu9KjAqCurMOPZ1Nd3Kwe4EMqcuXru+uvu71M6PnlD5pUh2/LHJiXQydNKgwgcN/Q96UuDxyfWwc14z3jgWtknL8WddhcA0RE4B4MovjPpWA9Rk="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "CUUe2C9hGoMqbZy+3SjVFCjPqNWc8xWaO4LOCt+97/4A0ubjG1wY3bO7aBX7rwI6i6RtBVt1CanSd1HAdv3HKmGcSTVqkPxJok40UmXqosj3PbqGzVKBLb13KNgBP29FX/U2HSoFLFqboOyWeEvReLcZ6l4m3cRZO76FaiMyYvqpoTL/NEj8AzrGe5yHgyoVzkKv2jyjk+s12Udo5qSWQQzS1zuPKedZoE3+keNQEq7cyZ2pGLUr34eYte6s6J8Qz8zCfm5yYfmNv2mlUYI8k4o/4SIgx+lNwzs1KFjJVfacdgrFsUN20h+cYNEYUHd3ER31oTfn6vOnVasahNPRvrQiZT3d77LCqBqIjk+Q9Ilt2M0NQAeK3T+3Md+makqF6vkpjdvmcMM1u14yFXzNCABoAyeZ8qy7Yp7jfAh0L31Hs+uMFQF8wKEoDrKDIKTe1+dhD8aj5xQPKkKuSw14u/vDHDwdFLgQPFkKAPVr28RMK69ArJ6JqiUR8Vrxg1M15i0X5d9FLFKtGGlVkbXD2bkJGUem5ZJVv+K/kDnQuuYT5y8nqCO/nak2sbe1qnqLXtQHFzpRV4rFUGNf8GSm7qz2iK82kOk3bpwQj0mtWQhzYPBP+03JBIBw1qtu4UN0vxDo3LzSjS81EW1ckPW9EmVsOx5sWOEUKOOtnQaGkOY="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "r6y18Nx4RZkLdRhLtCynJGPSJ1jXPDm9sDUXk34vH67WGXrjlfZEVOrEFV5oMpfx0ls1vQniCmQ8GQiBgF814T3xPz7wAMQU6YsukbMbwYXrGbu1BjRw2ewfEWAggg6kmKWYXqjo4gEFUeDMciswyoePMcM0/SHA1V5zG9bHxoeYbRLZTCtNNA72SAc7CT3Bh/7O8x4FXwqYuvsbznBL7kF7D1+IPW4GYiiVA3AHyPANNQefnIC3O659FP0o2cjh0YThoC6HzZ0cMhVgwPy/hKOMkUjEoPsL1iTQX+X08St0PcgR+FKzgM2Xev24tzmjZ1aR2CChEb/6iHiLTOew2tufSoJgzuaGQVwATZnxuynnSGx8Unmkt2Ux2+WQNWaG0/f+CC2cTGPqDiNjDb/LQaELuMj++2+756iN8gnDy3Cg5wOqmv8KO+8SMjupYTR/3Ve5nsCjxst5dIktXiZzwrnhdv76A4HpBztq0CNtjaakfileCbSnxFhdGk4e4nwW0YuCNHYuB8WESrrkdXFnEKjunCwQzIydh4cL3ZJM/SMKrnta898Fhxyk5UU6Nduc4AGn0KlBeffo50MijYdS9e7EpnaaVaC+vjxQhlzbFlKSFBC7Z6INQ6FxUHrfngbz12ZVCTnKMEYsL2Fy3KdPBOddyi2+BBf473cAQ0lDxf8="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "ZWcBKiUWt5EprjeIr63Jrw1qtWQ33i4egnVdLyCGPMiC0wkvQlxQfne6vEDqf0DV0WQfhq1Tp+tuxGTOHmwR5ONIqdWbpVeI4ydm+VVzU1Mz38aIV6CrAyPyCObYVURDH33cjiNnS8pVhhFOUuXHpY2oxAPetPI7ypG/2HyV1m0jgRx9d+5dt/UWYbjefT+YVC7K+5dKpUN9hVc78ws7Hs0rVZ8uM7SO7/x2Fr6czMoC18F8ifRlBUs8ztrMX/2b1Gx5JyPUqFfVbtwPFobxqWlvI9XeMmb+zUfLGu9DSWVjWsLDldj1q7zXBB59uyKUfnu3z/w1x0ZA1Hef1umAc1xfFs8yZxluVzLOrkGXvg53vQjxSComZ+BmIX7s4/14uGSUCYuUioxsiX+hXL/RMqHoZ9arioNq2k8m6RBC1ONLzIKfbXuHAX218JRPlddqLmhy4Y0F3GE1Pjqddgr+VTblLrHmcoMZjlnrCy03QHBZzwdZC0/POmIURCLKuwIgTyHGnilWBD1I9QQLs1txAfhPHoS2jr3gWEM9dxZPsPVU0wU33BAx3+MJRrnESQH855VyQkKD+wzKzz22fAY3q63YqICPI9BA4D4eA4RV4XrFVEoS4zPaMxNKlx9JjAs7SGNCVIdRn2E848E7MKw/Wxyd3WK4Hi8CgHalhQkGUmQ="
